services:
- name: pgbouncer-prod-ssl-2
  type: pserv
  plan: pro
  env: docker
  numInstances: 1
  autoDeploy: false
  pullRequestPreviewsEnabled: false
  envVars:
    - fromGroup: pgbouncer
    - key: DATABASE_URL
      sync: false

- name: global-db-pgbouncer-ssl
  type: pserv
  plan: pro
  env: docker
  numInstances: 1
  autoDeploy: false
  pullRequestPreviewsEnabled: false
  envVars:
    - fromGroup: pgbouncer
    - key: DATABASE_URL
      sync: false

- name: eu-to-us-fdw-pgbouncer
  type: pserv
  plan: pro
  env: docker
  numInstances: 1
  autoDeploy: false
  pullRequestPreviewsEnabled: false
  envVars:
    - key: DATABASE_URL
      sync: false
    - key: DEFAULT_POOL_SIZE
      value: 50
    - key: MAX_CLIENT_CONN
      value: 650
    - key: MAX_DB_CONNECTIONS
      value: 150
    - key: MIN_POOL_SIZE
      value: 10
    - key: ADMIN_USERS
      value: waterhead
    - key: AUTH_FILE
      value: /etc/secrets/userlist.txt
    - key: CLIENT_TLS_CA_FILE
      value: /etc/secrets/client.ca.crt
    - key: CLIENT_TLS_CERT_FILE
      value: /etc/secrets/client.tls.crt
    - key: CLIENT_TLS_KEY_FILE
      value: /etc/secrets/client.tls.key
    - key: CLIENT_TLS_SSLMODE
      value: require
    - key: POOL_MODE
      value: transaction
    - key: PORT
      value: 5432
    - key: SERVER_RESET_QUERY
      value: DISCARD ALL
    - key: SERVER_TLS_SSLMODE
      value: require
    - key: STATS_USERS
      value: datadog,opentelemetry_collector

envVarGroups:
  - name: pgbouncer
    envVars:
      - key: ADMIN_USERS
        value: waterhead
      - key: AUTH_FILE
        value: /etc/secrets/userlist.txt
      - key: CLIENT_TLS_CA_FILE
        value: /etc/secrets/client.ca.crt
      - key: CLIENT_TLS_CERT_FILE
        value: /etc/secrets/client.tls.crt
      - key: CLIENT_TLS_KEY_FILE
        value: /etc/secrets/client.tls.key
      - key: CLIENT_TLS_SSLMODE
        value: require
      - key: DEFAULT_POOL_SIZE
        value: 379
      - key: MAX_CLIENT_CONN
        value: 5000
      - key: MAX_DB_CONNECTIONS
        value: 379
      - key: MIN_POOL_SIZE
        value: 256
      - key: POOL_MODE
        value: transaction
      - key: PORT
        value: 5432
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: SERVER_TLS_SSLMODE
        value: require
      - key: STATS_USERS
        value: datadog,opentelemetry_collector
