name: Docker Build Image

on:
  pull_request:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Cloud SQL Auth Proxy image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: cloud-sql-auth-proxy:test
